---

- hosts: all
  name: Setup server
  become: true
  tasks:
    - name: Check If Docker Is Installed
      ansible.builtin.command: docker --version
      register: docker_valid
      ignore_errors: true
      changed_when: false

    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
          - apt-transport-https
        state: present
        update_cache: true

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_valid.failed

    - name: Get Ubuntu release version
      ansible.builtin.command: lsb_release -cs
      register: ubuntu_version
      changed_when: false

    - name: Get architecture
      ansible.builtin.command: dpkg --print-architecture
      register: architecture
      changed_when: false

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present
        filename: docker
      when: docker_valid.failed

    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install Docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: true

    - name: Copy .env file
      ansible.builtin.copy:
        src: ../../profile/.env
        dest: .env
        remote_src: false
        mode: '0755'


    - name: Copy docker compose file
      ansible.builtin.copy:
        src: ../../profile/docker-compose-dev.yml
        dest: docker-compose-dev.yml
        remote_src: false
        mode: '0644'

    - name: Run docker compose
      ansible.builtin.command: docker compose --env-file .env -f docker-compose-dev.yml up -d
      changed_when: true
